Repository rossyman/svelte-add-jest, pull requests merged in 2021-07, with the labels that each got.

#6 Update README and bump deps
  README.md
  package.json
  preset.ts
Labels: documentation

#7 Fix conflicting Jest dependencies
  package.json
  preset.ts
Labels: bug

#8 Add JSONC support
  README.md
  package.json
  preset.ts
Labels: bug, documentation

#9 Move JSON-C dependency from dev-only
  package.json
Labels: bug

#10 Rollback JSON-C changes
  README.md
  package.json
  preset.ts
Labels: bug

#11 Bump version for v1.1.3 bugfix
  package.json
Labels: bug

#13 fix moduleNameMapper $app paths
  package.json
  templates/jest.config.json
Labels: bug
